### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by candied-apple** [OfficialDonut/VisualBukkit#111]
OS : Archlinux
WM: Hyprland
```
[2024-02-16 17:16:17.714] [INFO] Visual Bukkit v6.0.1
[2024-02-16 17:16:18.004] [INFO] Loading extensions
[2024-02-16 17:16:18.119] [INFO] Loading initial project
[2024-02-16 17:16:18.662] [INFO] gRPC server running on port 50051 (unencrypted)
[2024-02-16 17:16:19.312] [SEVERE] An unexpected error occurred
java.lang.IllegalArgumentException: Unrecognized calling convention: 63
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:429)
	at com.sun.jna.Function.invoke(Function.java:364)
	at com.sun.jna.Library$Handler.invoke(Library.java:270)
	at jdk.proxy2/jdk.proxy2.$Proxy8.DiscordCreate(Unknown Source)
	at com.gmail.visualbukkit.VisualBukkitApp.updateDiscordActivity(VisualBukkitApp.java:451)
	at com.gmail.visualbukkit.VisualBukkitApp.lambda$start$26(VisualBukkitApp.java:265)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by OfficialDonut** [comment]
Fixed in 6.0.2
