### ISSUE TITLE
Cant open VB

### ISSUE THREAD

**Issue by jkalter24** [OfficialDonut/VisualBukkit#27]
Gives me an error any time I attempt to launch then closes
![image](https://user-images.githubusercontent.com/70232140/116624066-457a9180-a915-11eb-97bf-c6a1385fed0f.png)
![image](https://user-images.githubusercontent.com/70232140/116624144-6642e700-a915-11eb-9dbf-cb86cff7f2a3.png)

 Error as Follows:

java.lang.NullPointerException
	at com.gmail.visualbukkit.extensions.ExtensionManager.loadExtensions(ExtensionManager.java:52)
	at com.gmail.visualbukkit.VisualBukkitApp.lambda$load$3(VisualBukkitApp.java:145)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by OfficialDonut** [comment]
Delete outdated extensions.
