### ISSUE TITLE
Plugin Enable not working

### ISSUE THREAD

**Issue by Hotampa** [OfficialDonut/VisualBukkit#44]
So the plugin enable event doesn't seem to work correctly. When the server starts it sends the following error message:

[18:14:56] [Server thread/WARN]: java.lang.ClassCastException: class org.bukkit.configuration.file.YamlConfiguration cannot be cast to class java.io.File (org.bukkit.configuration.file.YamlConfiguration is in unnamed module of loader 'app'; java.io.File is in module java.base of loader 'bootstrap')
[18:14:56] [Server thread/WARN]: 	at vb.$worldy.PluginMain.onEnable(PluginMain.java:21)
[18:14:56] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:14:56] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[18:14:56] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:14:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[18:14:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[18:14:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[18:14:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[18:14:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[18:14:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[18:14:56] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[18:14:56] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ghost** [comment]
VB Support discord: https://discord.gg/b4bM9dSgue

**Comment by tmrxdev** [comment]
Please send this to VB Support discord because its not an program issue but an from you and on github you only can post issues from the program
