### ISSUE TITLE
Unable to open Visual Bukkit

### ISSUE THREAD

**Issue by zahadneokurkycz** [OfficialDonut/VisualBukkit#75]
I installed all visual bukkit extensions, I restarted app and now I am unable to open app - it shows me this error:

```
java.lang.UnsupportedClassVersionError: com/gmail/visualbukkit/extensions/vault/VaultExtension has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.gmail.visualbukkit.extensions.ExtensionManager.init(ExtensionManager.java:93)
	at com.gmail.visualbukkit.VisualBukkit.load(VisualBukkit.java:129)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

```

Screenshot:
![image](https://user-images.githubusercontent.com/78108685/184983835-fcca45da-921a-484e-b27f-170945734976.png)

**Comment by shmezi** [comment]
Are you using the latest visual bukkit app and the latest extensions?

**Comment by Minemobs** [comment]
You need to install java 17

**Comment by shmezi** [comment]
> You need to install java 17

Kinda doubt that's the issue. Most likely incompatible extensions. VB bundles java with it.
